### ISSUE TITLE
1.12:  Fatal errors were detected during the transition from SERVER_ABOUT_TO_START to SERVER_STARTING.

### ISSUE THREAD

**Issue by tachometer74** [Ivorforce/PandorasBox#13]
Log is here:  https://pastebin.com/VPW3XWVa

If I disable Pandora's Box then the game launches without error.

MC 1.12
Forge 14.21.1.2413

**Comment by Ivorforce** [comment]
Oh right, I forgot to address this.

Duplicate of #12. Gonna fix in a second.
